server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: fixit-notifications

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}

twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  phone-number: ${TWILIO_PHONE_NUMBER}

rabbit:
  queues:
    task-assigned: fixit.notifications.task.assigned
    task-completed: fixit.notifications.task.completed